version: 2.1

parameters:
  run-workflow-a:
    type: boolean
    default: false
  run-workflow-b:
    type: boolean
    default: false

jobs:
  buildjob:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test"
  buildjob2:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test2"

workflows:
  workflow-a:
    when:
      or: [<< pipeline.parameters.run-workflow-a >>]
    jobs:
      - buildjob
  workflow-b:
    when:
      or: [<< pipeline.parameters.run-workflow-b >>]
    jobs:
      - buildjob2